# Generated by Django 5.1.1 on 2024-09-29 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Integrantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_integrante', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/integrantes')),
                ('conteudo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SobreNos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('conteudo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventosPublicacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_post', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/eventos_publicacoes')),
                ('conteudo', models.TextField()),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
