# Generated by Django 5.1.1 on 2024-10-03 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrando_fronteiras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerhero',
            options={'verbose_name': 'Conteúdo', 'verbose_name_plural': 'Banner Hero'},
        ),
        migrations.AlterModelOptions(
            name='eventospublicacoes',
            options={'ordering': ['slug'], 'verbose_name': 'Evento e Publicação', 'verbose_name_plural': 'Eventos e Publicações'},
        ),
        migrations.AlterModelOptions(
            name='integrantes',
            options={'ordering': ['slug'], 'verbose_name': 'Integrante', 'verbose_name_plural': 'Integrantes'},
        ),
        migrations.AlterModelOptions(
            name='sobrenos',
            options={'verbose_name': 'Conteúdo', 'verbose_name_plural': 'Sobre Nós'},
        ),
        migrations.AlterField(
            model_name='bannerhero',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Tamamnho para ser usado: 1169x1136px', null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='eventospublicacoes',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='eventospublicacoes',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='eventospublicacoes',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Tamanho recomendado da imagem: 530x392px', null=True, upload_to='eventos_publicacoes', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='eventospublicacoes',
            name='nome_post',
            field=models.CharField(max_length=255, verbose_name='Nome do Post'),
        ),
        migrations.AlterField(
            model_name='eventospublicacoes',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='integrantes',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='integrantes',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Tamanho recomendado da imagem: 349x474px', null=True, upload_to='integrantes', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='integrantes',
            name='nome_integrante',
            field=models.CharField(max_length=100, verbose_name='Nome do Integrante'),
        ),
        migrations.AlterField(
            model_name='integrantes',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='sobrenos',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='sobrenos',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Tamanho recomendado da imagem: 576x411px', null=True, upload_to='', verbose_name='Imagem'),
        ),
    ]
